const c = ['Sabar','Yang Sopan Lah Kontol','Apa Sih','Gak Jelas','Astaufirullah','Tobat Goblok','Lu Waras??','Gajelas','gua tandain muka lu','Anak Dakjal Lu Ngak Sopan','Neraka Menantimu','Dahlah Sesat','menahan emosi','Gak Sopan Bener Dah','Anda Terdeteksi Tidak *WARAS*','Toxic Mulu Dah','Dasar Anak Manusia Biadab','Harap Bersabar Ini Ujian🗿','Tobat Lah Wahai Manusia Durhaka','Tutor Toxic Dek!','Wah Sepuh Neraka Ini','Semangat Toxicnya Gwe Tunggu Di Neraka:)','Lanjutkan Bakatmu Nak!','Waow.... Bocil Epep Lagi Toxic🗿','Ada yang tidak beres ama ni anak, Harus di rukiah si ini🗿']
const d = ['Love You Too Cyng🗿','Iya Sayang!...','Iya Bebz','Anak Pinter!...','Aku Juga Kangen!😣','Iya Iya Bhawel','Diam Lebih Baik','Sabar','Nyimak!','Ih Ada Wibu🗿']

export async function before(m) {
	if (m.text.toLowerCase() == "jancok") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "bacot") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "bct") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "ngwe") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "ngewe") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "ngentot") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "ngntt") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "ngent") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "jnck") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "tolol") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "tlol") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "ajg") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "anjing") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "babi") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "bbi") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "goblok") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "gblk") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "mmk") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "memek") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "pukimak") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "bapakmu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "bapaklu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "bpkmu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "bpklu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "mmkmu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "mamakmu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "mmklu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "mamaklu") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "bajingan") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "monyet") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "mnyet") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "celeng") await this.reply(m.chat, c.getRandom(), m)
    if (m.text.toLowerCase() == "pukimak") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "kontol") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "kntl") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "kintil") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "janda") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "duda") await this.reply(m.chat, c.getRandom(), m)
	
	if (m.text.toLowerCase() == "sayang") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "kenapa sayang") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "ayok sayang") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "wibu") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "i love you") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "yang") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "yah") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "sabar") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "dosa") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "loh") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "putus") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "diputusin") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "kacang") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "dikacangin") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "ngak nyambung") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "tobat") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "iya sayang") await this.reply(m.chat, d.getRandom(), m)
	if (m.text.toLowerCase() == "bagus") await this.reply(m.chat, c.getRandom(), m)
	if (m.text.toLowerCase() == "ngak mau") await this.reply(m.chat, c.getRandom(), m)
	return !0
}
